# Generated by Django 3.0.8 on 2020-08-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200802_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('clip', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('description', models.TextField()),
            ],
        ),
    ]
