# Generated by Django 3.0.8 on 2020-08-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
