# Generated by Django 3.0.8 on 2020-08-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video',
            new_name='banner',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
