# Generated by Django 3.0.8 on 2020-08-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200802_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.FileField(blank=True, upload_to='banners/%Y/%m/%d/'),
        ),
    ]
